add pario for sfc
ClaraDraper-NOAA/GSI pull request #1
Opened 2024-01-23 15:39 UTC by tsga

**Description**

**Type of change**

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

  
**Checklist**

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

2024-01-23 16:19 UTC, tsga commented
Note: the parallel write (paranc) appears slower than the non-paranc, especially for write_atm in the "writeincrements_panc" subroutine. Tested for C96E48 and C384E192.

2024-01-25 15:43 UTC, ClaraDraper-NOAA requested changes
This is close, thanks. A few things: 
1. remove all added indentation 
2. delete, rather than comment out.

2024-01-25 15:43 UTC, ClaraDraper-NOAA commented on src/enkf/controlvec.f90
> +   if (nproc == 0) then
Is this change necessary?

2024-01-25 15:43 UTC, ClaraDraper-NOAA commented on src/enkf/controlvec.f90
>        call readgriddata(nanal1(nproc),nanal2(nproc),cvars3d,cvars2d,nc3d,nc2d,clevels,ncdim,nbackgrounds, &
As above.

2024-01-25 15:43 UTC, ClaraDraper-NOAA commented on src/enkf/gridio_gfs.f90
> +
delete extra line

2024-01-25 15:43 UTC, ClaraDraper-NOAA commented on src/enkf/gridio_gfs.f90
> -
Add line back.

2024-01-25 15:43 UTC, ClaraDraper-NOAA commented on src/enkf/gridio_gfs.f90
> +   ! if (read_sfc_file) then
remove commented out block.

2024-01-25 15:43 UTC, ClaraDraper-NOAA commented on src/enkf/gridio_gfs.f90
> +  !sfcfilename = trim(adjustl(datapath))//trim(adjustl(filesfcprefixes(nb)))//trim(charnanal)
This was not actually being used, right?

2024-01-25 15:43 UTC, ClaraDraper-NOAA commented on src/enkf/gridio_gfs.f90
> -  if (.not. isinitialized) call init_spec_vars(nlons,nlats,ntrunc,4)
revert the indent here.

2024-01-25 18:29 UTC, tsga commented
- Removed commented out lines
- Fixed indentation to match previous code
- All changed lines now show new/modified code

2024-02-22 23:04 UTC, ClaraDraper-NOAA approved these changes
Looks great! Please prepare a PR with your changes for EMC's GSI code base. 

I think it'll be cleanest for you to merge your changes into the latest develop, rather than for me to merge your branch into mine (since I made some changes when mine was reviewed, which will now be merge conflicts).

2024-02-22 23:04 UTC, ClaraDraper-NOAA commented on src/enkf/controlvec.f90
> +     print *,'time in write_control parnc on root',t2-t1,'secs'
change to paranc

2024-02-22 23:04 UTC, ClaraDraper-NOAA commented on src/enkf/gridio_gfs.f90
> +     write(6,*)'READGRIDDATA_PNC sfc:  ***FATAL ERROR*** parallel read only supported for netCDF' , ' PROGRAM STOPS'
Check the logic elsewhere, but I think paranc means netcfdf only - so we don't really need this check.

2024-02-22 23:04 UTC, ClaraDraper-NOAA commented on src/enkf/gridio_gfs.f90
> +  if (write_atm_file ) then   ! do only sfc write?
remove this comment (and ask me about it, if you're not sure).

2024-02-22 23:04 UTC, ClaraDraper-NOAA commented on src/enkf/gridio_gfs.f90
> +  call nccheck_incr(nf90_close(ncid_out))
why is this new?

2024-02-23 12:56 UTC, tsga commented on src/enkf/gridio_gfs.f90
> +     write(6,*)'READGRIDDATA_PNC sfc:  ***FATAL ERROR*** parallel read only supported for netCDF' , ' PROGRAM STOPS'
it is also present in the atm section so keeping it to be consistent

2024-02-26 14:14 UTC, closed without merging